server:
    port: 8083
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        url: jdbc:postgresql://localhost:5433/db_deal
        username: postgres
    jpa:
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-offset-reset: earliest
            create-documents: conveyor-create-documents
            credit-issued: conveyor-credit-issued
            finish-registration: conveyor-finish-registration
            group-id: my-group
            send-documents: conveyor-send-documents
            send-ses: conveyor-send-ses
    mail:
        host: smtp.gmail.com
        password: mfedzqhftgzrfzlm
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: loanconveyor2@gmail.com

    config:
        additional-location:
                    credit-application: file:/D:\\programming\\LoanConveyorApp\\credit-application.txt
                    credit-contact: file:/D:\\programming\\LoanConveyorApp\\credit-contact.txt
                    credit-payment-schedule: file:/D:\programming\LoanConveyorApp\credit-payment-schedule.txt
